# Generated by Django 4.2.5 on 2023-09-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-placed_at'], 'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
